import time

time.sleep(2)
print('All work and no play makes Jack a dull boy.')
print('All work and no play makes Jack a dull boy.')
time.sleep(1)
print('All work and no play makes Jack a dull boy.')
print('All work and no play makes Jack a dull boy.')
time.sleep(1)
print('All work and no play makes Jack a dull boy.')
print('All work and no play makes Jack a dull boy.')
time.sleep(1)
print('All work and no play makes Jack a dull boy.')
print('All work and no play makes Jack a dull boy.')
time.sleep(1)
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
time.sleep(1)
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
time.sleep(1)
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
time.sleep(1)
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
print('ALL WORK AND NO PLAY MAKES JACK A DULL BOY.')
time.sleep(1)
print('All   work  and  no  play  makes  Jack  a  dull  boy')
print('All   work  and  no  play  makes  Jack  a  dull  boy')
time.sleep(1)
print('All   work  and  no  play  makes  Jack  a  dull  boy')
print('All   work  and  no  play  makes  Jack  a  dull  boy')
time.sleep(1)
print('All   work  and  no  play  makes  Jack  a  dull  boy')
print('All   work  and  no  play  makes  Jack  a  dull  boy')
time.sleep(1)
print('All   work  and  no  play  makes  Jack  a  dull  boy')
print('All   work  and  no  play  makes  Jack  a  dull  boy')
time.sleep(1)
print('All   work  and  no  play  makes  Jack  a  dull  boy')
print('All   work  and  no  play  makes  Jack  a  dull  boy')
time.sleep(1)
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
time.sleep(1)
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
time.sleep(1)
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
time.sleep(1)
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
time.sleep(1)
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
time.sleep(1)
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
time.sleep(1)
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
print('All     work    and    no    play    makes    Jack    a    dull    boy.')
time.sleep(1)